spring:
    data:
        mongodb:
            username: root
            password: mongo123
            host: 127.0.0.1    
            database: server-auth-db
            authentication-database: admin
    application:
        name: AUTH-SERVICE

server:
    port: 8092

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost